### ISSUE TITLE
`cargo build` fails on Rust 1.79.0

### ISSUE THREAD

**Issue by bgilbert** [MitMaro/captur#3]
```console
error: lint `or_patterns_back_compat` has been renamed to `rust_2021_incompatible_or_patterns`
  --> src/lib.rs:24:2
   |
24 |     or_patterns_back_compat,
   |     ^^^^^^^^^^^^^^^^^^^^^^^ help: use the new name: `rust_2021_incompatible_or_patterns`
   |
note: the lint level is defined here
  --> src/lib.rs:7:2
   |
7  |     warnings
   |     ^^^^^^^^
   = note: `#[deny(renamed_and_removed_lints)]` implied by `#[deny(warnings)]`

error: could not compile `captur` (lib) due to 1 previous error
```

**Comment by MitMaro** [comment]
Thanks for the report!

I have some strict linting on this project that really needs to be updated. This should be an easy fix to warn during build, and only error out in CI.

**Comment by MitMaro** [comment]
Alright, this is fixed as part of #6 , but I have some other cleanup that I want to do before pushing out a new release. I'll close this issue once the new release is published.

Thanks again for the report!

**Comment by bgilbert** [comment]
Awesome, thanks for the quick response!

**Comment by MitMaro** [comment]
https://github.com/MitMaro/captur/releases/tag/1.0.0 has been created and published to crates.io
